### ISSUE TITLE
Consider replacing capybara-webkit with poltergeist

### ISSUE THREAD

**Issue by monfresh** [18F/dolores-landingham-bot#113]
This repo is currently using v1.x of capybara-webkit, which results in the following warning when running the specs:
```
WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.7.
```
If you're planning on upgrading to v2 of capybara-webkit when it comes out, then it will require anyone who is contributing to this repo to have Qt 5.0 installed on their machine, which in turn requires the full Xcode app to be installed.

Having to download a multi-gigabyte app just to be able to run some tests is not a great developer experience IMO. Instead, I recommend switching to [Poltergeist](https://github.com/teampoltergeist/poltergeist), which does not depend on Xcode, and works just as well as capybara-webkit. In some ways, it's even better because it does not require `xvfb`, and makes running tests on Travis or Vagrant easier.

Here is an example of the changes required to make the switch: https://github.com/codeforamerica/ohana-web-search/pull/601/files

**Comment by jessieay** [comment]
@monfresh good idea, just added the "help wanted" tag to indicate that this issue is ready for development

**Comment by jessieay** [comment]
@monfresh thank you for the suggestion. merged to master at https://github.com/18F/dolores-landingham-bot/commit/b971d8f4b61fa9bd285d286f8d2e8c3f01f83ffc -- thank you to @fentie for the PR!
