### ISSUE TITLE
Needs basic styles

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#12]
While I love minimal styling, the current complete lack of grid/styles does make this app feel a little less than user friendly. Perhaps we can throw in a basic grid framework and styles that make the forms easier to navigate

**Comment by gemfarmer** [comment]
* [ ] Add SCSS
* [ ] Add grid
* [ ] Style existing forms

**Comment by jessieay** [comment]
Since #18 is merged, this issue has been addressed. Closing. :hammer:
