### ISSUE TITLE
Explore intermittently failing specs

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#122]
This branch failed here: https://travis-ci.org/18F/dolores-landingham-bot/builds/94793132

but then passed on other runs without any code changes. I suspect this is related to timezones.

**Comment by ccostino** [comment]
If this is related to the timezones I wouldn't expect to see so many other failing specs.  When I last ran into a similar issue (testing at a certain time at night, at least in EST), it was only a couple of specs that failed.  This is described in more detail here in #111.

In looking at the Travis log, a whole bunch of stuff bombed that's unrelated, mainly with undefined methods.  Could the build itself have just failed, thus causing problems when trying to run the tests afterward?

**Comment by jessieay** [comment]
oh yes the build I linked to was related to updated *all* gems and having some deprecated RSpec matchers in there. There was another failure with just 2 failed specs. But not I cannot find it! Darn

**Comment by jessieay** [comment]
that build with the 2 failing specs was deployed later in the evening last Friday, so I suspect it was the same issue Carlo saw before. Perhaps a testing strategy would be to set current time to 7pm PT or something

**Comment by ccostino** [comment]
Okay that definitely sounds like the timezone issue then, that makes sense! :-)
