### ISSUE TITLE
Cannot add new employees

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#127]
Getting two error messages whenever I try to add any new employee:

Could not create employee
There is not a slack user with the username "username" in your org.

Things I did that may have caused this:
- deleted "melodykramer" and tried to readd "melodykramer"
- added a PIF who is not part of 18F org. (Got second error message.)

**Comment by jessieay** [comment]
@gemfarmer I think this was fixed, right?

**Comment by gemfarmer** [comment]
@jessieay yes. Closing
