### ISSUE TITLE
Pagination causing problems with display

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#128]
Paginating the list of employees is leading to a few issues:
* not all employees are listed
* others are listed twice

This is annoying because it __looks__ llike a user doesn't exist, but they actually do, so we are tempted to create a new user, but a record with that `slack_username` exists and nothing is changed.

I am proposing that we, in the interest of simple approaches, remove the pagination and add a filter functionality to quickly find users.

@melodykramer @jessieay @ccostino thoughts?

**Comment by melodykramer** [comment]
That works for me!

**Comment by ccostino** [comment]
@gemfarmer:  I'm in favor of this as well; the pagination was added only as a quick stop-gap to prevent the pages from growing too long, but clearly it's not quite working right.  Adding a filter mechanism is definitely a good idea to keep things manageable, with or without pagination!

**Comment by monfresh** [comment]
I'm pretty sure this is due to sorting by a non-unique key (`started_on`). Postgres doesn't guarantee the same sort order when multiple records have the same value for the column that is being used to sort. You can test this theory by sorting by Employee id instead.

**Comment by jessieay** [comment]
ah yes! we should sort by `created_at` instead

**Comment by ccostino** [comment]
D'oh!  Thanks for the clarification, @monfresh!  Perhaps we could reinvestigate this after the filtering is done because it would be helpful as more employees and messages are added, and especially as more messages are sent and recorded.

**Comment by jessieay** [comment]
@gemfarmer is this fixed now?

**Comment by gemfarmer** [comment]
@jessieay The pagination should be gone, but I kept the issue open because based on @monfresh and @ccostino's  comments, it might be a good idea to re-introduce pagination in addition to the filtering. Thoughts?

**Comment by gemfarmer** [comment]
I just reintroduced pagination and pushed it live with #138
