### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by knagode** [18F/dolores-landingham-bot#131]
When visit on https://dolores-app.18f.gov/, fill in my info for registration (or use google authentication) I am redirected to page with error:

URL:
https://dolores-app.18f.gov/auth/myusa/callback?code=c08bd2b41cd6cbbde175e5394824530a1065ca3cea9ab5a435de260fa7fc102b&state=ac5018a98d38fd0814c0577ba8a638ab48d2f72fda6782ad

Page error:
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.

Will this be fixed soon or should I check it on local machine?

**Comment by jessieay** [comment]
Hi @knagode are you authenticating with a `@gsa.gov` email address? 

The deployed app requires you to have a GSA email address. See: https://github.com/18F/dolores-landingham-bot/blob/823871cd04e72db5d76aa7f1dfa78a067146aa9d/app/controllers/auth_controller.rb#L19

If you do not have a gsa email address and would like to use this app, I suggest setting it up locally and updating the auth controller.

**Comment by knagode** [comment]
OK, will try to run it locally then. Thanks!

**Comment by jessieay** [comment]
Let us know if you have any other questions. Closing this issue for now. :earth_asia:
