### ISSUE TITLE
Filter for sent schedule messages is broken.

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#137]
Now that SentScheduleMessages is back up, it is clear that the filter isn't working. Even though it was at one point. sigh

**Comment by jessieay** [comment]
what are you putting into filter to search? would be helpful info for someone trying to help out with this issue

**Comment by gemfarmer** [comment]
@jessieay Sure. Any attempt to filter by `slack_username` or `sent_on` does not reduce the displayed records.

Don't start working on this though, I fixed it this afternoon and will push and make a PR shortly or tomorrow morning.
