### ISSUE TITLE
Ability to delete a message

### ISSUE THREAD

**Issue by nicoleslaw** [18F/dolores-landingham-bot#142]
As the onboarding lead, I need to be able to delete messages that are no longer important or relevant (or, in today's case, added by mistake).

**Comment by jessieay** [comment]
To clarify for whoever works on this (probably future me) - this should be possible for users who are admins only.

**Comment by jbcden** [comment]
Hello! I thought I'd try my hand at this issue but I am having trouble getting setup. I have been following the instructions in the contributing documentation; however, I am getting a message stating that: `The requested scope is invalid, unknown, or malformed.` I am definitely being redirected to `/auth/myusa` by the `authenticate!` action but I'm not sure why I am failing to be authenticated. I created an application in MyUsa and added the generated keys to the `.env` file. Any thoughts? I would really love to be able to contribute!
PS I also changed then `is_permitted` method in the `AuthController` to accept non-.gov emails and my `.foreman` file does have the port set to 5000. Thanks in advance!

**Comment by SukhGrewal** [comment]
Assume this is for Slack
Would you consider our product VEOCI that already has these and other features that teams need? WE developed Veoci with ten years of experience at GE on what teams need to get their work done. The ability to keep a messaging space clean was one of the first things we did - in real work, it is needed. For example, if someone types in a wrong IP address, you want that corrected and not mislead people for the next year.
VEOCI is a different paradigm from Slack.  But you can get your work done including delete and edit messages if you have the authorization. It is a messaging backbone for work.
For a small onboarding application, we could set you up in minutes.

**Comment by jessieay** [comment]
Hi @SukhGrewal - our team already uses Slack so we are not looking to develop on onboarding application on a different platform.

**Comment by jbcden** [comment]
@jessieay, @nicoleslaw I have opened https://github.com/18F/dolores-landingham-bot/pull/147 to address this issue. Please let me know if there are any problems.

**Comment by jessieay** [comment]
@nicoleslaw this is live on prod!

**Comment by nicoleslaw** [comment]
:+1:

**Comment by jessieay** [comment]
big thank you to @jbcden for stepping in to volunteer on this one. Woot woot! :rainbow:

**Comment by gemfarmer** [comment]
Thanks @jbcden !
