### ISSUE TITLE
Setup troubles

### ISSUE THREAD

**Issue by jbcden** [18F/dolores-landingham-bot#146]
Hello! I thought I'd try my hand at contributing to [this](https://github.com/18F/dolores-landingham-bot/issues/142) but I am having trouble getting setup. I have been following the instructions in the contributing documentation; however, I am getting a message stating that: `The requested scope is invalid, unknown, or malformed.` I am definitely being redirected to `/auth/myusa` by the `authenticate!` action but I'm not sure why I am failing to be authenticated. I created an application in MyUsa and added the generated keys to the `.env` file. Any thoughts? I would really love to be able to contribute!
PS I also changed then `is_permitted` method in the `AuthController` to accept non-.gov emails and my `.foreman` file does have the port set to 5000. Thanks in advance!

**Comment by jbcden** [comment]
I am also seeing
```
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
```
when I look in the Chrome console.

**Comment by jessieay** [comment]
Hi @jbcden ! Thank you for chiming in and helping out with the bot. Getting you up and running will help ensure the docs are clear / comprehensive for future developers who want to get going on Dolores, so it's a win-win from our perspective. Apologies if it is frustrating for you. 

One question about your MyUSA app: did you check the "email" box when setting up your myusa app? That is the scope we are asking for and it sounds like the error you're seeing is related to myusa. 

Also, if you are running your app on port 5000, did you add the correct URLs to our myusa app setup?

This is what I have in myusa:

![screen shot 2016-02-26 at 10 24 51 am](https://cloud.githubusercontent.com/assets/601515/13361386/3e4b82c6-dc73-11e5-9332-b214aafd3a3d.png)

If you confirm that all of these settings are working, we can work together to debug more.

**Comment by jbcden** [comment]
@jessieay aha! I had not checked the email box and I also had the first url as just: `http://localhost:5000`. Thanks so much for the quick reply. I would be happy to submit a PR to update the documentation. I think the main points of confusion were the urls and checking the email scope.

**Comment by gemfarmer** [comment]
@jbcden based on your recent PRs, I imagine this is no longer an issue? Also, as Jessie already said, thanks for contributing!

**Comment by jbcden** [comment]
@gemfarmer I am all set now. I will open a PR later this week to update the documentation.

**Comment by gemfarmer** [comment]
@jbcden gotcha. I'll leave this issue open then.

**Comment by jessieay** [comment]
https://github.com/18F/dolores-landingham-bot/pull/152 closes this and was merged -- so I am closing manually :)
