### ISSUE TITLE
Sort table by date and time

### ISSUE THREAD

**Issue by nicoleslaw** [18F/dolores-landingham-bot#151]
As the onboarding lead, I need to be able to see the messages at a glance. Right now, they are sorted by date, but the time is ~random. Example below:

![screen shot 2016-03-03 at 10 16 28 am](https://cloud.githubusercontent.com/assets/94900/13498727/271363fc-e129-11e5-93dd-7d72abf0dce9.png)

**Comment by jessieay** [comment]
Hey @nicoleslaw - agreed, messages should be default be sorted in ascending `day_count` and `time` order. 

@gemfarmer weren't you working on something related to sorting records at one point?

**Comment by gemfarmer** [comment]
@jessieay I was, but I wasn't getting this specific. I can't get to this next week, but I can put it on my todo list and get to it asap, @nicoleslaw

**Comment by jessieay** [comment]
cool. I think the first step would be to update default sorting to be ascending day count AND time. second step could be more complicated sorting stuff.

**Comment by gemfarmer** [comment]
Agreed. I'll approach the default first and merge it as its own PR, then if all goes well we can add some sort of sort UI.

**Comment by jbcden** [comment]
@gemfarmer I could implement the default sort if that would be helpful.

**Comment by gemfarmer** [comment]
@jbcden if you have the time, that would be great! Thanks for pitching in!

**Comment by jessieay** [comment]
this is now live on production -- thank you @jbcden for your continued contributions!
