### ISSUE TITLE
Include Pull Request Template

### ISSUE THREAD

**Issue by fentie** [18F/dolores-landingham-bot#163]
Now that Github supports pull request templates, I think this would be a useful thing to include in order to minimize rework on incoming PRs. 

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by jessieay** [comment]
love this idea!

**Comment by gemfarmer** [comment]
agreed!

**Comment by jessieay** [comment]
Closed via #169 -- definitely looking forward to trying this out -- let us know if you have any suggestions for how to improve our template, @fentie

**Comment by fentie** [comment]
That looks pretty good, yeah. At my current place we have a few different PR templates for different repos, but in general they cover one or more of the following:

- What
- Why
- How to test
- Relevant documentation/links
- Special deploy instructions

Feel free to include any that seem useful. This can always evolve as it goes.

 I've also noticed at least a few PRs here having a "Minor" section too, is that worth pulling forward here or is that not commonly used?

**Comment by jessieay** [comment]
@fentie thanks for your input. I myself use "minor" to indicate smaller changes that are perhaps not related to the current PR but were cleaned up in the process. Not sure we need to codify that via PR template but perhaps...

**Comment by fentie** [comment]
Sounds like there's no need. Cheers 8^)
