### ISSUE TITLE
Readme missing Google Doc Link

### ISSUE THREAD

**Issue by dijonkitchen** [18F/dolores-landingham-bot#164]
Under Usage Instructions for 18-F employees, in the first item under "To add new messages": https://github.com/18F/dolores-landingham-bot#usage-instructions-for-18f-employees

**Comment by jessieay** [comment]
good call! and we've changed the process so that people add new messages in this github issue: https://github.com/18F/dolores-landingham-bot/issues/115

so I will mark this issue as "help wanted" so someone can update the non-linked google doc to be a link to that github issue

**Comment by dijonkitchen** [comment]
Updated!
