### ISSUE TITLE
Validation on slack_username character length

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#175]
When attempting to add a new employee, slack usernames that are less than 3 characters trigger a pre-flash validation error. 

This is possibly the result of a default validation in [this `rails-i18n` file](https://github.com/18F/dolores-landingham-bot/blob/master/config/locales/en.yml#L22) or [the employee model](https://github.com/18F/dolores-landingham-bot/blob/master/app/models/employee.rb#L9)

The same validation error is also triggered properly when you use trailing whitespace or special characters.

<img width="336" alt="screen shot 2016-05-10 at 11 49 46 am" src="https://cloud.githubusercontent.com/assets/4803473/15153930/d878d72e-16a0-11e6-93a6-36928c43ff93.png">

**Comment by jessieay** [comment]
Closed via https://github.com/18F/dolores-landingham-bot/pull/185 -- thanks @cwarden !
