### ISSUE TITLE
Handle regular policy reminders

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#180]
This is here as a reminder to investigate further, not as an actionable ticket.

From @batemapf via slack
> hey folks - i am interested in automating some of the regular policy reminders that ops and other teams need to send out. for instance, we manually send quarterly reminders about not starting work for clients until we have a signed agreement. would be great to have this delivered automagically to each individual at the best possible time (i.e. taking into account time zones, work patterns). extra points if the recipient can confirm they understand or raise a hand if they don't / have a question. any suggestions on the above?

@ccostino:
> Oh interesting, that would essentially be adding functionality to @mrs_landingham to send repeat messages at set intervals.

me:
> there is also an issue already to handle two way communication. (edited)
> This would be a little odd because it pertains to a particular message itself instead of being a stand alone question.

**Comment by jessieay** [comment]
This seems right in line with Mrs. Landingham's core purpose!

Implementation brainstorm:

Add a new `message_type` column to `scheduled_messages` -- if it is an `onboarding` message it gets sent once. If it is `quarterly` then we send it out on the first day of each quarter.

**Comment by jessieay** [comment]
### Requirements for this feature:

#### Description:

Given that I am an admin
And I am logged in
When I visit the new_scheduled_messages path 
And I add a title and message body to a scheduled message
And select 'quarterly' as the message type
Then the 'Business days after employee starts to send message' and 'Time of day to send message (uses employee's local time zone)' fields cannot be filled out 
And the message should be sent on October 1, January 1, April 1 and July 1
If any if the above dates is on a weekend, it should send the message on the following Monday

#### Testing requirements

At least one capybara end-to-end test for the above functionality (see `spec/features` directory for other capybara tests)

Unit tests for any new underlying functionality (RSpec)

### Suggested implementation (not required)

We are already using the `holidays` gem, which you can use to make sure messages don't get sent out on a weekend https://github.com/18F/dolores-landingham-bot/blob/master/Gemfile#L25

Regular messages are for onboarding purposes and are only sent once. Now that we are introducing a new type of message. I would call the new column on `scheduled_messages` `type` have it be an ActiveRecord enum that defaults to `onboarding` but can also be set to `quarterly` (like in the case for this feature)

Once `quarterly` is selected, the other fields that are specific to onboarding-type messages ( 'Business days after employee starts to send message' and 'Time of day to send message (uses employee's local time zone)')  can either be hidden or disabled. whatever is easier.

**Comment by batemapf** [comment]
hey folks - could we build in the requirement that the employee actively acknowledge receipt of the message / interact with the bot? i.e. 👍 for i received it; 💯 for i completed it; ❓ for i need more information, etc..? not sure if data (responses) can generated based on user action (as opposed to admin action), but if so, that'd be super cool!

**Comment by jessieay** [comment]
We will need to update the description I gave to @mtorres253 but yes this is possible:

We are already using the real-time message API.
Docs on that: https://github.com/dblock/slack-ruby-client#realtime-client

What we need to flesh out here is "what happens" when each of the above situations -- if we can give specific instructions on those, we can incorporate into this auction. Otherwise, it might make sense to do it separately after we've decided exactly what we want to happen when someone replies to a quarterly message.

**Comment by scottt2** [comment]
Hey folks! Just to clarify, the ack functionality that @batemapf suggested--while being totally awesome--is **not** in scope for this, right?

Just double checking.

Thanks!

**Comment by jessieay** [comment]
@scott2 yes, this auction does not include the ability to respond to messages. We have not scoped that part of this functionality quite yet. Thanks for asking!

**Comment by scottt2** [comment]
@jessieay Right on. Thanks for the clarification!

**Comment by jessieay** [comment]
Merged to master at 4de847866f9d56baed7aea4ea31048ff335fb13a
