### ISSUE TITLE
Holiday Weeks

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#19]
Hey!

Thought popped into my head this AM: sometimes there's a holiday, in which case I think we'd want to bump messages to the following day. This isn't necessary for v.1 - but just wanted to bring to your attention. :)

https://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/federal-holidays/#url=2015

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/kfmucSt3

**Comment by jessieay** [comment]
we should skip over weekends and federal holidays. should automate skipping of weekends

**Comment by jessieay** [comment]
will need to re-number scheduled messages before deploying this.

**Comment by melodykramer** [comment]
How so? I'm putting in a ton more messages right now and am happy to renumber as I go.

**Comment by jessieay** [comment]
We can provide more specific instructions once this is implemented (@gemfarmer is currently working on it)

The idea, generally, would be that messages would be numbered according to sequence and would automatically skip weekends and holidays.

so instead of day counts and week days looking like:

1 - Monday
2 - Tuesday
3 - Weds
4 - Thurs
5 - Friday
9 - Monday
10 - Tues

it would be:

1 - Monday
2 - Tuesday
3 - Weds
4 - Thurs
5 - Friday
6 - Monday
7 - Tues

**Comment by melodykramer** [comment]
Sounds good. Let me redo these and I'll ping here when that's finished.

**Comment by jessieay** [comment]
@melodykramer don't do it quite yet! Brian is still working on making the above numbering a reality so we should renumber when we are ready to deploy changes

**Comment by melodykramer** [comment]
I will wait! Just let me know when to switch - it'll be easy once you say "Go!"

**Comment by melodykramer** [comment]
@jessieay Does that new numbering account for holidays that change dates? For example:

Week 1 Day 1 of 2016, 2017, 2018 is always an off day.
Thanksgiving is Month 11 Fourth Thursday - so that date changes.

I think what you've outlined skips weekends but I'm not sure it accounts for the holidays.

**Comment by melodykramer** [comment]
I'm looking now to see if Mailchimp has tackled this - I'm sure this is a problem that has been solved before.

**Comment by bennovack** [comment]
Do you have a definitive online calendar of holidays you could link in?

**Comment by jessieay** [comment]
@melodykramer brian is looking into how to deal with holidays. We discussed possibly having them be manually added at first. there are probably some ruby gems out there that deal with calculating the changing dates on a year to year basis as well

**Comment by melodykramer** [comment]
Oh! Cool, here's the manual list - I'm happy to add it: 

https://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/federal-holidays/

And here's a post I found about skipping holidays:

http://blog.mailup.com/2014/02/triggered-messages-weekends-holidays/

**Comment by cllns** [comment]
The [`business_time`](https://github.com/bokmann/business_time) gem might help, and it has a section on its README about integrating with the [`holidays`](https://github.com/holidays/holidays) gem

**Comment by melodykramer** [comment]
:+1: @cllns and @bennovack Thanks!

**Comment by melodykramer** [comment]
Going to close https://github.com/18F/dolores-landingham-bot/issues/91 because it's folded into here. Also adding @gemfarmer to this issue as assignee. Dolores is on hiatus until this is resolved, I think.

**Comment by gemfarmer** [comment]
@melodykramer Thanks! 
@cllns @bennovack I was thinking about potentially manually adding blackout dates instead of relying on a gem. 
My thinking here is that 18F has several non-holiday do-not-disturb days, this might give us more control. Of course, maybe a dual approach would work. Add gems + additional blackout dates.

Thoughts?

**Comment by cllns** [comment]
It looks like `holidays` [has support](https://github.com/holidays/holidays#loading-custom-definitions-on-the-fly) for adding custom 'holidays'. The only trouble is that it get confusing, since they're not really holidays. Maybe preface the custom holidays with '[do-not-disturb]' or something?

**Comment by melodykramer** [comment]
I don't mind adding blackout dates manually, @gemfarmer - there aren't that many federal holidays + offsites.

**Comment by ccostino** [comment]
Awesome suggestion on the gems!  It got me thinking about the timezone support added in a while back, and when I looked into the `business_time` some more I saw this note:

> This can lead to some [weird] looking effects if, say, you are in the Eastern time zone but doing everything in UTC times… Your business day will appear to start and end at 9:00 and 5:00 UTC. If this seems perplexing to you, I can almost guarantee you are in over your head with timezones in other ways too, this is just the first place you encountered it. Timezone relative date handling gets more and more complicated every time you look at it and takes a long time before it starts to seem simple again.

...Yeah, that about sums it up. :-)
