### ISSUE TITLE
Should there be a password?

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#25]
Can anyone see the full message history? If so, I think there should be some kind of login or password, to limit this to 18F employees.

**Comment by mbland** [comment]
Yeah, since it seems there's not yet a straightforward way to produce a secure, exclusive pipe from the oauth2_proxy to the app running in Cloud Foundry, this may be the way to go, at least in the near-term.

**Comment by jessieay** [comment]
Adding basic auth until we get full on auth for the app: https://github.com/18F/dolores-landingham-bot/pull/26
