### ISSUE TITLE
Format messages in case of special characters

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#30]
https://api.slack.com/docs/formatting

**Comment by gemfarmer** [comment]
https://slack.zendesk.com/hc/en-us/articles/202288908-Formatting-your-messages

**Comment by jessieay** [comment]
@gemfarmer That zendesk thread is relevant to Slack users, but there are a few chars that need to be escaped when sending messages via the API:

```
Messages can contain any displayable Unicode sequence of characters (all messages must use UTF-8 encoding), but need to be slightly escaped by clients. Before sending messages to the server, clients should make the following transforms:

& replaced with &amp;
< replaced with &lt;
> replaced with &gt;
```

**Comment by ccostino** [comment]
I wonder if we need to escape just those three characters or others - judging by the guide it looks like just those 3 but I wanted to confirm since the fix will currently escape anything (&, <, >, ", ', etc.).

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/k6o83IWq
