### ISSUE TITLE
Make Application Publicly Accessible

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#31]
The app created through MyUSA is currently privately accessible only to developers on this project. We need to make it "Public", then screen only for gsa.gov email addresses.

**Comment by jessieay** [comment]
@gemfarmer looks like Yoz fixed this? (saw mention in Slack bot room about this)

**Comment by gemfarmer** [comment]
Yup. I made a request to make it public and put in the logic to screen for gsa.gov email accounts here:
https://github.com/18F/dolores-landingham-bot/commit/7f686ef0573710b1f5558288ba67c1cfafecfc89
