### ISSUE TITLE
Validation on slack username

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#33]
when someone enters a slack username for an employee record, we should validate that it does not have an `@` at the beginning

**Comment by gemfarmer** [comment]
Slightly more complicated, but this should also validate that that slack user exists. On top of that, and this might be a new issue, we should store the slack user id so that if they change their slack "name", it doesn't throw off our reference.

**Comment by ccostino** [comment]
Is there a specific format that a Slack username must be, e.g., only letters, alpha-numeric, etc.?  I've been trying to sift through the documentation looking for an answer.

**Comment by ccostino** [comment]
I found it right in the profile settings:  "Usernames must be lowercase and cannot contain spaces."  So it looks like lowercase alpha only.

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/MCGArovt

**Comment by jessieay** [comment]
Via Carlo:

Upon further research it's not just lowercase letters as I see folks with underscores, numbers, etc., it's just that the letters have to be (or are just converted automatically) to lowercase. I still haven't been able to pin-point documentation that specifies what characters are specifically allowed, I'll keep searching for a bit.

**Comment by ccostino** [comment]
Looks like to validate a username it should just be a call for looking up user info and checking for the user_not_found error: https://api.slack.com/methods/users.info

**Comment by ccostino** [comment]
Okay, there's a simpler solution as we already retrieve the list of users and search through that - I'm going to leverage that functionality and build from there!

**Comment by ccostino** [comment]
@gemfarmer, I think the storing of the Slack user ID should be separate from this and may not necessarily be needed for this particular use case (though I think it's still a good idea anyway).

**Comment by jessieay** [comment]
Merged at https://github.com/18F/dolores-landingham-bot/commit/823871cd04e72db5d76aa7f1dfa78a067146aa9d
