### ISSUE TITLE
Create staging environment

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#41]
Create a new CF app `dolores-staging` to deploy to `dolores-staging.18f.gov`. @mbland do you need anything from me in order to host `dolores-staging.18f.gov`
* [x] add `dolores-staging` CF app
* [x] add `dolores-staging` CF route 
* [x] hosting set up
* [x] create new MyUSA app `dolores-staging`
* [x] update CF env variables, including app keys from MyUSA app
* [x] update docs

**Comment by jessieay** [comment]
closing in favor of https://trello.com/c/BMWgaVH7
