### ISSUE TITLE
Provide ability to test messages

### ISSUE THREAD

**Issue by ccostino** [18F/dolores-landingham-bot#45]
As someone who is configuring the Dolores Landhingham bot, I would like the ability to test the message I am creating so that I can see that it is formatted correctly in Slack itself.

We could provide a test link next to the edit link in the messages list, and there may be a couple of ways of accomplishing this:

* If you're logged into the app, having it automatically send them to just you as you test.
* Providing the ability to specify a person(s) who would also like to test/preview the messages.

**Comment by gemfarmer** [comment]
@ccostino Great idea. This would be useful for devs and the person creating the messages.

Because our authentication doesn't know what your slack username is, I think it would be best to allow the tester to specify a default slack name that would receive test messages.

**Comment by jessieay** [comment]
If I think about my own use cases for sending a test message, it's mostly to send a message to myself so that I can see the formatting (which is what @ccostino mentioned, too). 

So, I think we can include a box for the slack username to send to in the "test a message" form.

**Comment by jessieay** [comment]
Working on this here; almost done https://github.com/18F/dolores-landingham-bot/compare/jy-test-messages?expand=1

**Comment by jessieay** [comment]
closing in favor of https://trello.com/c/RafIoY6J
