### ISSUE TITLE
Update "Contributing" doc

### ISSUE THREAD

**Issue by gemfarmer** [18F/dolores-landingham-bot#49]
Add to contributing: 
* [x] " check to make sure foreman is set to run at port 5000. If it is not, you will not be able to be authenticated with MyUSA. "
* [x] In authentication section, link to https://alpha.my.usa.gov/applications to make sure you are on the list of allowed local developers

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/RJNEBDNv (moved card to "up next")
