### ISSUE TITLE
Only certain people can create messages

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#53]
all people w/a GSA email address should be able to auth into Dolores, but we want to whitelist certain people to be able to create messages. Not sure exactly how that's done with our auth setup

**Comment by ccostino** [comment]
Another question I have:  does our auth setup currently have a means of managing roles and/or permissions, or is that something we will have to build into the app itself?

**Comment by jessieay** [comment]
@gemfarmer set up MyUSA, perahps he has some suggestions on this?

**Comment by melodykramer** [comment]
This is super important - I don't think we want a scenario where anyone can go in and change previous messages — particularly because they're designed as a block of material.

**Comment by jessieay** [comment]
agreed - going to come up with the quickest / easiest solution I can think of and go with that for now. Def a top development priority

**Comment by jessieay** [comment]
I think the best plan of attack would be to create users in the database similar to how C2 does it with MyUSA: https://github.com/18F/C2/blob/91231060f7c32e31ea3332368ed0fb86316f01e6/app/controllers/auth_controller.rb#L5

the auth hash contains the email address. Then, we can manually set certain users as admins and only those users will be able to create / edit messages.

Melody, what about creating / updating employees? Should that also be for admins only? and what about testing messages? I'd like to keep the app as open as possible to all users while also providing necessary safeguards.

**Comment by melodykramer** [comment]
I think anyone should be able to update employees - because people might want to duck out of the bot messages, and should be allowed to do so.

Testing messages - everyone as well, I think.

**Comment by jessieay** [comment]
Started work on this here https://github.com/18F/dolores-landingham-bot/compare/jy-1-based-counting?expand=1

**Comment by melodykramer** [comment]
Editing + adding messages = some employees.
Updating employees = all employees.
Testing messages = all employees.

**Comment by jessieay** [comment]
addressed via https://github.com/18F/dolores-landingham-bot/pull/141 -- closing
