### ISSUE TITLE
Document that messages should start on "day 0"

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#69]
See slack convo for reference: https://18f.slack.com/archives/bots/p1444832532000002

We should document (in readme?) that the "day count" for a message is how many days sine the employee started a message should be send out. so we are doing zero-based counting

**Comment by andrewmaier** [comment]
Let's start on day 1 :) https://18f.slack.com/archives/bots/p1444933820000053

**Comment by melodykramer** [comment]
I don't care which of these was decided upon - but there's conflicting info here. Did we decide on 0 or 1?

**Comment by jessieay** [comment]
The current implementation is "Day 0" - will move to starting on Day 1 and document that when I get a chance. For now, start on Day 0 and I will update all of the messages when I change the day count stuff :)

**Comment by melodykramer** [comment]
I'm actually fine with keeping it as Day 0. It makes sense in my head, as their starting day. And +1, is first day +1 - it's actually easier to keep track of. So my vote is keep as is, and just note that :)

**Comment by jessieay** [comment]
started work on this here https://github.com/18F/dolores-landingham-bot/compare/jy-1-based-counting?expand=1 (going to complete as part of the larger story of having admin users)

**Comment by jessieay** [comment]
This was addressed via https://github.com/18F/dolores-landingham-bot/pull/103
