### ISSUE TITLE
Improve flash message when test message send fails

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#73]
Melody tried to send a test message to herself and the message failed. The current error message is:

`"Could not update employee with the Slack username you entered. Please make sure there is an employee record for the username listed in #{employees_path}"`

The error occurs when there is no employee record for the slack username entered into the test message box.

Seems like we could improve this error message to make the meaning more clear (I think we meant to use "find" instead of "update" anyway...that's a clear mistake). 

Suggestions on how to make this error message wording more clear?

@melodykramer

**Comment by melodykramer** [comment]
Oops! Looks like that employee isn't in the system yet! Make sure you've entered the Slack handle for that employee.
