### ISSUE TITLE
Save Slack channel ID in DB

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#74]
we do a query each time we send a message to get the slack channel ID for a user. We should save this on the `employee` record so we don't need to hit the slack API each time we send a message

**Comment by rjewell2200** [comment]
@jessieay I submitted a PR to fix this issue: https://github.com/18F/dolores-landingham-bot/pull/156

**Comment by jessieay** [comment]
this is now live on prod and working like a charm - thanks @rjewell2200 ! This is going to save us a lot of API requests :)

**Comment by rjewell2200** [comment]
@jessieay Awesome! Happy to help!
