### ISSUE TITLE
Update formatting in messages#index

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#75]
we show the whole message body now, which looks wacky when the message is long:

![screen shot 2015-10-16 at 11 32 24 am](https://cloud.githubusercontent.com/assets/601515/10550095/a773bcd8-73f9-11e5-8681-58bda6220164.png)

**Comment by jessieay** [comment]
@melodykramer you agree that we should just show the first bit of the message on this page and allow someone to view the whole thing by clicking on the title?

**Comment by melodykramer** [comment]
Yes, @jessieay - first bit is fine!
