### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#8]
We need some kind of auth for this app so people don't start trolling us via Dolores.

See Mike's suggestion here: https://github.com/18F/dolores-landingham-bot/issues/2#issuecomment-141159857

I would also be OK with basic Rails authentication for this alpha version: http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html -- but we should double check that there wouldn't be a problem with us using that due to this being a gov website.

**Comment by jessieay** [comment]
@gemfarmer I think this could be a good one for you to tackle after reviewing my PR :)

**Comment by gemfarmer** [comment]
Todo:
* [x] Add DNS listing
* [x] Configure routes on Cloud Foundry
* [ ] Add routing rules to CF
* [ ] Authenticate within the Rails app using custom request header `HTTP_X_FORWARDED_EMAIL`
