### ISSUE TITLE
no @ is required for Slack names

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#81]
make note of this in docs and/or form for adding employees

**Comment by melodykramer** [comment]
One other thing: no spaces can be after the username, either. :)

**Comment by jessieay** [comment]
to implement this, we should add a form validation that does not allow an `@` or a space after the username when filling out the employee#new form (or creating data in general)

**Comment by jbcden** [comment]
@jessieay perhaps I am misunderstanding but doesn't https://github.com/18F/dolores-landingham-bot/blob/master/app/models/employee.rb#L6 do what you are describing? Or do you mean more on the front-end side of things?

**Comment by jessieay** [comment]
yeah I think more of a frontend prompt. I believe right now you get an activerecord validation if the format is wrong but it would be nice to let a person creating an `employee` that the `slacker_username` field should contain the username without an `@`. clients-side validations would also be cool

**Comment by jbcden** [comment]
If no one else gets to this, I would be happy to work on it.

**Comment by jbcden** [comment]
While working on this I noticed that HTML5 validations were disabled in the `simple_form` configurations; is there a reason for this? I was planning on using those but if you have disabled them for a reason I can just use some javascript. Thoughts @jessieay?

**Comment by jessieay** [comment]
@jbcden I am not sure why they were disabled...fine with adding them back in unless others object
