### ISSUE TITLE
Dolores App needs at least 1GB of memory in production

### ISSUE THREAD

**Issue by ccostino** [18F/dolores-landingham-bot#82]
An issue cropped up today when @melodykramer tried to save a new message and the app crashed and responded with a 500 error code.  In looking at the logs with @afeld we discovered two things:  the app had crashed with an out of memory error, and the current memory limit of the app is set to 512MB.

We need to change the memory limit to be at least 1GB in the app manifest.yml file.

**Comment by afeld** [comment]
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#memory
