### ISSUE TITLE
where are the messages in the repo?

### ISSUE THREAD

**Issue by leahbannon** [18F/dolores-landingham-bot#84]
Hi - I'd like to file a PR against something in the message I just got from the bot. But I can't find that in the repo. Putting this in the README would be super helpful, too.

**Comment by jessieay** [comment]
Hey @leahbannon  - the message are in a database.You can auth at dolores-app.18f.gov with your GSA email and see the list of scheduled messages

If there is a small typo or problem, you can update the message there. If it is something larger, perhaps you can leave a comment here and @andrewmaier / @melodykramer can address it.

There is a future plan to only allow certain people to create / edit messages (https://github.com/18F/dolores-landingham-bot/issues/53) but for now anyone at 18F can auth and edit.

**Comment by jessieay** [comment]
This does bring up an interesting point - ideally we could have some sort of version control on the message content. We could add papertrail (https://github.com/airblade/paper_trail) to keep a complete record of message history/changes, but what we care about here is less keeping track of history and more making sure that changes are going through some sort of review / peer editing process.

**Comment by melodykramer** [comment]
@leahbannon Please let me know what you'd like to change.

**Comment by leahbannon** [comment]
Sure thing. I was going to change "she or he" to "they" so it's not gender binary. And then check other messages for that as well.

**Comment by melodykramer** [comment]
I will make those changes right now. It only affected message 1.

**Comment by jessieay** [comment]
Since this appears to be resolved, I am closing this issue. Thanks all! :100:
