### ISSUE TITLE
Update design

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#85]
Jessie started a branch here -- https://github.com/18F/dolores-landingham-bot/tree/jy-style-fun

This replaces our current design setup with the bourbon/neat gems. The style on that branch looks pretty much the same as what we have no but with less code.

Next step would be to improve the readability of the views.

**Comment by gemfarmer** [comment]
@jessieay just so you know I picked up where you left off and have been styling the site to be in line with the recently released [18F Branding](https://pages-staging.18f.gov/brand/visual-style/)

**Comment by ccostino** [comment]
@gemfarmer:  Thank you!  I haven't had the time to tackle this at all and appreciate you jumping in on it.

**Comment by gemfarmer** [comment]
Np. I haven't had much time to work on it this week, but I like where it is going.

**Comment by gemfarmer** [comment]
Closed with #145
