### ISSUE TITLE
Way to add new message and push every other message down a day?

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#92]
I realized I'd like to add a message for week 1 and shift every other message by a day. I don't think this is currently possible, but would make a nice feature (Or the ability to move the messages in a different order.)

**Comment by ccostino** [comment]
@melodykramer:  I had thought some about the idea of sending multiple messages a day when I was working on the time of day and time zone support, and it sounds like it'd be a good thing to add support for general message priority.

It could be as simple as adding a priority or order field to messages and just setting the overall order of all of them.  This would keep it separate from how many days after the start or the time of day a given message should go out.

Thinking out loud a bit here, theoretically you'd be able to even have multiple messages go out at roughly the same time but in a specified order.  When processing the messages, we'd just have to sort them in the order of priority - the DailyMessageSender should probably be renamed to something a bit more descriptive of what it is actually doing now.

**Comment by ccostino** [comment]
@melodykramer: You're also asking for all other messages to shift back a day though when inserting a new one into the mix that should go out before others.  Perhaps it could be worked in that by default it does that but we provide an option to override and not adjust the day to send a message out (or vice versa).

**Comment by melodykramer** [comment]
Yes, maybe the time/date is decoupled from the message orders.

A >>> B >>>> C 

and then somewhere else

Monday >>> Tuesday >>> Wednesday is a holiday...so Thursday

**Comment by melodykramer** [comment]
I'm closing this because having the ability to add time gives us the ability to do this.
